### ISSUE TITLE
0.4.1: java.lang.NoClassDefFoundError: org/jboss/netty/channel/group/ChannelGroup

### ISSUE THREAD

**Issue by arosien** [n8han/herald#1]
(M=2631f) arosien@pv139150 ~/asr/sniff> herald
Getting net.java.dev.jna jna 3.2.3 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    1 artifacts copied, 0 already retrieved (838kB/24ms)
Getting Scala 2.9.1 (for herald-app)...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    4 artifacts copied, 0 already retrieved (19939kB/534ms)
Getting net.databinder.herald herald-app_2.9.1 0.4.1 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    12 artifacts copied, 0 already retrieved (1710kB/52ms)
java.lang.NoClassDefFoundError: org/jboss/netty/channel/group/ChannelGroup
    at unfiltered.netty.Http$.apply(servers.scala:36)
    at unfiltered.netty.Http$.local(servers.scala:41)
    at unfiltered.netty.Http$.anylocal(servers.scala:43)
    at herald.Preview$.apply(preview.scala:9)
    at herald.Herald$$anonfun$4$$anonfun$apply$13.apply(herald.scala:156)
    at herald.Herald$$anonfun$4$$anonfun$apply$13.apply(herald.scala:154)
    at scala.Either$RightProjection.map(Either.scala:285)
    at herald.Herald$$anonfun$4.apply(herald.scala:154)
    at herald.Herald$$anonfun$4.apply(herald.scala:153)
    at scala.Either$RightProjection.flatMap(Either.scala:277)
    at herald.Herald$.run(herald.scala:153)
    at herald.Herald.run(herald.scala:173)
    at herald.Herald.run(herald.scala:171)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.channel.group.ChannelGroup
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 20 more
Error during sbt execution: java.lang.NoClassDefFoundError: org/jboss/netty/channel/group/ChannelGroup

**Comment by arosien** [comment]
Previously:

(fix-norbert-mirroring=cbc33 *1 ?2) arosien@pv139150 ~/box/box-common> cs n8han/herald
Getting net.databinder.herald herald-app_2.9.1 0.4.1 ...
downloading http://repo1.maven.org/maven2/net/databinder/herald/herald-app_2.9.1/0.4.1/herald-app_2.9.1-0.4.1.jar ...
    [SUCCESSFUL ] net.databinder.herald#herald-app_2.9.1;0.4.1!herald-app_2.9.1.jar (1487ms)
downloading http://repo1.maven.org/maven2/net/databinder/unfiltered-netty-server_2.9.1/0.6.0/unfiltered-netty-server_2.9.1-0.6.0.jar ...
    [SUCCESSFUL ] net.databinder#unfiltered-netty-server_2.9.1;0.6.0!unfiltered-netty-server_2.9.1.jar (1470ms)
downloading http://repo1.maven.org/maven2/net/databinder/dispatch/core_2.9.1/0.9.0-alpha2/core_2.9.1-0.9.0-alpha2.jar ...
    [SUCCESSFUL ] net.databinder.dispatch#core_2.9.1;0.9.0-alpha2!core_2.9.1.jar (1905ms)
downloading http://repo1.maven.org/maven2/org/slf4j/slf4j-jdk14/1.6.2/slf4j-jdk14-1.6.2.jar ...
    [SUCCESSFUL ] org.slf4j#slf4j-jdk14;1.6.2!slf4j-jdk14.jar (988ms)
downloading http://repo1.maven.org/maven2/net/databinder/unfiltered-netty_2.9.1/0.6.0/unfiltered-netty_2.9.1-0.6.0.jar ...
    [SUCCESSFUL ] net.databinder#unfiltered-netty_2.9.1;0.6.0!unfiltered-netty_2.9.1.jar (1394ms)
downloading http://repo1.maven.org/maven2/net/databinder/unfiltered-util_2.9.1/0.6.0/unfiltered-util_2.9.1-0.6.0.jar ...
    [SUCCESSFUL ] net.databinder#unfiltered-util_2.9.1;0.6.0!unfiltered-util_2.9.1.jar (992ms)
downloading http://repo1.maven.org/maven2/net/databinder/unfiltered_2.9.1/0.6.0/unfiltered_2.9.1-0.6.0.jar ...
    [SUCCESSFUL ] net.databinder#unfiltered_2.9.1;0.6.0!unfiltered_2.9.1.jar (7492ms)
downloading http://repo1.maven.org/maven2/io/netty/netty/3.3.1.Final/netty-3.3.1.Final.jar ...
    [SUCCESSFUL ] io.netty#netty;3.3.1.Final!netty.jar(bundle) (13092ms)
downloading http://repo1.maven.org/maven2/com/ning/async-http-client/1.7.0/async-http-client-1.7.0.jar ...
    [SUCCESSFUL ] com.ning#async-http-client;1.7.0!async-http-client.jar (5895ms)
downloading http://repo1.maven.org/maven2/org/jboss/netty/netty/3.2.7.Final/netty-3.2.7.Final.jar ...
    [SUCCESSFUL ] org.jboss.netty#netty;3.2.7.Final!netty.jar(bundle) (6764ms)
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    12 artifacts copied, 0 already retrieved (1710kB/93ms)
herald is ready to go

Conscripted n8han/herald to /Users/arosien/bin/herald

**Comment by n8han** [comment]
do a

```
cs --clean-boot
```

then try your preview again, please.

**Comment by arosien** [comment]
Same problem:

1 (M=2631f) arosien@pv139150 ~/asr/sniff> cs --clean-boot
Getting Scala 2.9.0-1 (for conscript)...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    4 artifacts copied, 0 already retrieved (20447kB/252ms)
Getting net.databinder conscript_2.9.0-1 0.3.1 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    13 artifacts copied, 0 already retrieved (2306kB/72ms)
Cleaned boot directory (/Users/arosien/.conscript/boot)
(M=2631f) arosien@pv139150 ~/asr/sniff> herald
Getting net.java.dev.jna jna 3.2.3 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    1 artifacts copied, 0 already retrieved (838kB/33ms)
Getting Scala 2.9.1 (for herald-app)...
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    4 artifacts copied, 0 already retrieved (19939kB/277ms)
Getting net.databinder.herald herald-app_2.9.1 0.4.1 ...
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    12 artifacts copied, 0 already retrieved (1710kB/51ms)
java.lang.NoClassDefFoundError: org/jboss/netty/channel/group/ChannelGroup
    at unfiltered.netty.Http$.apply(servers.scala:36)
    at unfiltered.netty.Http$.local(servers.scala:41)
    at unfiltered.netty.Http$.anylocal(servers.scala:43)
    at herald.Preview$.apply(preview.scala:9)
    at herald.Herald$$anonfun$4$$anonfun$apply$13.apply(herald.scala:156)
    at herald.Herald$$anonfun$4$$anonfun$apply$13.apply(herald.scala:154)
    at scala.Either$RightProjection.map(Either.scala:285)
    at herald.Herald$$anonfun$4.apply(herald.scala:154)
    at herald.Herald$$anonfun$4.apply(herald.scala:153)
    at scala.Either$RightProjection.flatMap(Either.scala:277)
    at herald.Herald$.run(herald.scala:153)
    at herald.Herald.run(herald.scala:173)
    at herald.Herald.run(herald.scala:171)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.channel.group.ChannelGroup
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 20 more
Error during sbt execution: java.lang.NoClassDefFoundError: org/jboss/netty/channel/group/ChannelGroup

**Comment by n8han** [comment]
Okay, could you try deleting your `~/.ivy2/cache` ? It is the root of most evil, especially evil of this nature. As you can possibly see, a required dependency is not being fetched and put on the classpath by the launcher, all of which is supposed to happen before herald runs a single instruction.

**Comment by arosien** [comment]
Same problem, after downloading the internet:

1 (M=2631f) arosien@pv139150 ~/asr/sniff> rm -rf ~/.ivy2/cache
!cs
(M=2631f) arosien@pv139150 ~/asr/sniff> !cs
cs --clean-boot
Getting Scala 2.9.0-1 (for conscript)...
downloading file:/Users/arosien/.m2/repository/org/scala-lang/scala-compiler/2.9.0-1/scala-compiler-2.9.0-1.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-compiler;2.9.0-1!scala-compiler.jar (392ms)
downloading file:/Users/arosien/.m2/repository/org/scala-lang/scala-library/2.9.0-1/scala-library-2.9.0-1.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-library;2.9.0-1!scala-library.jar (281ms)
downloading http://scala-tools.org/repo-releases/org/scala-lang/jline/2.9.0-1/jline-2.9.0-1.jar ...
    [SUCCESSFUL ] org.scala-lang#jline;2.9.0-1!jline.jar (3976ms)
downloading http://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.4/jansi-1.4.jar ...
    [SUCCESSFUL ] org.fusesource.jansi#jansi;1.4!jansi.jar (1369ms)
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    4 artifacts copied, 0 already retrieved (20447kB/254ms)
Waiting for lock on /Users/arosien/.ivy2/.sbt.ivy.lock to be available...
Getting net.databinder conscript_2.9.0-1 0.3.1 ...
downloading http://scala-tools.org/repo-releases/net/databinder/conscript_2.9.0-1/0.3.1/conscript_2.9.0-1-0.3.1.jar ...
    [SUCCESSFUL ] net.databinder#conscript_2.9.0-1;0.3.1!conscript_2.9.0-1.jar (2507ms)
downloading http://scala-tools.org/repo-releases/net/databinder/dispatch-http_2.9.0-1/0.8.3/dispatch-http_2.9.0-1-0.8.3.jar ...
    [SUCCESSFUL ] net.databinder#dispatch-http_2.9.0-1;0.8.3!dispatch-http_2.9.0-1.jar (881ms)
downloading http://scala-tools.org/repo-releases/net/databinder/dispatch-lift-json_2.9.0-1/0.8.3/dispatch-lift-json_2.9.0-1-0.8.3.jar ...
    [SUCCESSFUL ] net.databinder#dispatch-lift-json_2.9.0-1;0.8.3!dispatch-lift-json_2.9.0-1.jar (1388ms)
downloading http://scala-tools.org/repo-releases/com/github/scopt/scopt_2.9.0-1/1.1.1/scopt_2.9.0-1-1.1.1.jar ...
    [SUCCESSFUL ] com.github.scopt#scopt_2.9.0-1;1.1.1!scopt_2.9.0-1.jar (1428ms)
downloading http://scala-tools.org/repo-releases/org/scala-lang/scala-swing/2.9.0-1/scala-swing-2.9.0-1.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-swing;2.9.0-1!scala-swing.jar (12259ms)
downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.1/httpclient-4.1.jar ...
    [SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.1!httpclient.jar (9879ms)
downloading http://scala-tools.org/repo-releases/net/databinder/dispatch-core_2.9.0-1/0.8.3/dispatch-core_2.9.0-1-0.8.3.jar ...
    [SUCCESSFUL ] net.databinder#dispatch-core_2.9.0-1;0.8.3!dispatch-core_2.9.0-1.jar (4249ms)
downloading http://scala-tools.org/repo-releases/net/databinder/dispatch-futures_2.9.0-1/0.8.3/dispatch-futures_2.9.0-1-0.8.3.jar ...
    [SUCCESSFUL ] net.databinder#dispatch-futures_2.9.0-1;0.8.3!dispatch-futures_2.9.0-1.jar (590ms)
downloading http://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.1/httpcore-4.1.jar ...
    [SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.1!httpcore.jar (2727ms)
downloading file:/Users/arosien/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar ...
    [SUCCESSFUL ] commons-logging#commons-logging;1.1.1!commons-logging.jar (52ms)
downloading http://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar ...
    [SUCCESSFUL ] commons-codec#commons-codec;1.4!commons-codec.jar (1447ms)
downloading http://scala-tools.org/repo-releases/net/liftweb/lift-json_2.8.1/2.3/lift-json_2.8.1-2.3.jar ...
    [SUCCESSFUL ] net.liftweb#lift-json_2.8.1;2.3!lift-json_2.8.1.jar (5141ms)
downloading http://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar ...
    [SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.3!paranamer.jar (1711ms)
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    13 artifacts copied, 0 already retrieved (2306kB/48ms)
Cleaned boot directory (/Users/arosien/.conscript/boot)
(M=2631f) arosien@pv139150 ~/asr/sniff> herald
Getting net.java.dev.jna jna 3.2.3 ...
downloading http://repo1.maven.org/maven2/net/java/dev/jna/jna/3.2.3/jna-3.2.3.jar ...
    [SUCCESSFUL ] net.java.dev.jna#jna;3.2.3!jna.jar (13939ms)
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    1 artifacts copied, 0 already retrieved (838kB/28ms)
Getting Scala 2.9.1 (for herald-app)...
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.9.1/scala-compiler-2.9.1.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-compiler;2.9.1!scala-compiler.jar (159918ms)
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.9.1/scala-library-2.9.1.jar ...
^C130 (M=2631f) arosien@pv139150 ~/asr/sniff> herald
Getting Scala 2.9.1 (for herald-app)...
downloading http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.9.1/scala-library-2.9.1.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-library;2.9.1!scala-library.jar (120810ms)
downloading http://repo1.maven.org/maven2/org/scala-lang/jline/2.9.1/jline-2.9.1.jar ...
    [SUCCESSFUL ] org.scala-lang#jline;2.9.1!jline.jar (3050ms)
:: retrieving :: org.scala-tools.sbt#boot-scala
    confs: [default]
    4 artifacts copied, 0 already retrieved (19939kB/266ms)
Getting net.databinder.herald herald-app_2.9.1 0.4.1 ...
downloading http://repo1.maven.org/maven2/net/databinder/herald/herald-app_2.9.1/0.4.1/herald-app_2.9.1-0.4.1.jar ...
    [SUCCESSFUL ] net.databinder.herald#herald-app_2.9.1;0.4.1!herald-app_2.9.1.jar (2657ms)
downloading http://repo1.maven.org/maven2/com/tristanhunt/knockoff_2.9.1/0.8.0-16/knockoff_2.9.1-0.8.0-16.jar ...
    [SUCCESSFUL ] com.tristanhunt#knockoff_2.9.1;0.8.0-16!knockoff_2.9.1.jar (6208ms)
downloading http://repo1.maven.org/maven2/net/databinder/unfiltered-netty-server_2.9.1/0.6.0/unfiltered-netty-server_2.9.1-0.6.0.jar ...
    [SUCCESSFUL ] net.databinder#unfiltered-netty-server_2.9.1;0.6.0!unfiltered-netty-server_2.9.1.jar (1626ms)
downloading http://repo1.maven.org/maven2/net/databinder/dispatch/core_2.9.1/0.9.0-alpha2/core_2.9.1-0.9.0-alpha2.jar ...
    [SUCCESSFUL ] net.databinder.dispatch#core_2.9.1;0.9.0-alpha2!core_2.9.1.jar (2062ms)
downloading http://repo1.maven.org/maven2/org/slf4j/slf4j-jdk14/1.6.2/slf4j-jdk14-1.6.2.jar ...
    [SUCCESSFUL ] org.slf4j#slf4j-jdk14;1.6.2!slf4j-jdk14.jar (1471ms)
downloading http://repo1.maven.org/maven2/net/databinder/unfiltered-netty_2.9.1/0.6.0/unfiltered-netty_2.9.1-0.6.0.jar ...
    [SUCCESSFUL ] net.databinder#unfiltered-netty_2.9.1;0.6.0!unfiltered-netty_2.9.1.jar (1507ms)
downloading http://repo1.maven.org/maven2/net/databinder/unfiltered-util_2.9.1/0.6.0/unfiltered-util_2.9.1-0.6.0.jar ...
    [SUCCESSFUL ] net.databinder#unfiltered-util_2.9.1;0.6.0!unfiltered-util_2.9.1.jar (1518ms)
downloading http://repo1.maven.org/maven2/net/databinder/unfiltered_2.9.1/0.6.0/unfiltered_2.9.1-0.6.0.jar ...
    [SUCCESSFUL ] net.databinder#unfiltered_2.9.1;0.6.0!unfiltered_2.9.1.jar (6591ms)
downloading http://repo1.maven.org/maven2/io/netty/netty/3.3.1.Final/netty-3.3.1.Final.jar ...
    [SUCCESSFUL ] io.netty#netty;3.3.1.Final!netty.jar(bundle) (12189ms)
downloading http://repo1.maven.org/maven2/org/scala-tools/testing/test-interface/0.5/test-interface-0.5.jar ...
    [SUCCESSFUL ] org.scala-tools.testing#test-interface;0.5!test-interface.jar (720ms)
downloading http://repo1.maven.org/maven2/com/ning/async-http-client/1.7.0/async-http-client-1.7.0.jar ...
    [SUCCESSFUL ] com.ning#async-http-client;1.7.0!async-http-client.jar (8826ms)
downloading http://repo1.maven.org/maven2/org/jboss/netty/netty/3.2.7.Final/netty-3.2.7.Final.jar ...
    [SUCCESSFUL ] org.jboss.netty#netty;3.2.7.Final!netty.jar(bundle) (12934ms)
downloading http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.6.2/slf4j-api-1.6.2.jar ...
    [SUCCESSFUL ] org.slf4j#slf4j-api;1.6.2!slf4j-api.jar (1038ms)
:: retrieving :: org.scala-tools.sbt#boot-app
    confs: [default]
    12 artifacts copied, 0 already retrieved (1710kB/36ms)
java.lang.NoClassDefFoundError: org/jboss/netty/channel/group/ChannelGroup
    at unfiltered.netty.Http$.apply(servers.scala:36)
    at unfiltered.netty.Http$.local(servers.scala:41)
    at unfiltered.netty.Http$.anylocal(servers.scala:43)
    at herald.Preview$.apply(preview.scala:9)
    at herald.Herald$$anonfun$4$$anonfun$apply$13.apply(herald.scala:156)
    at herald.Herald$$anonfun$4$$anonfun$apply$13.apply(herald.scala:154)
    at scala.Either$RightProjection.map(Either.scala:285)
    at herald.Herald$$anonfun$4.apply(herald.scala:154)
    at herald.Herald$$anonfun$4.apply(herald.scala:153)
    at scala.Either$RightProjection.flatMap(Either.scala:277)
    at herald.Herald$.run(herald.scala:153)
    at herald.Herald.run(herald.scala:173)
    at herald.Herald.run(herald.scala:171)
    at xsbt.boot.Launch$.run(Launch.scala:54)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:43)
    at xsbt.boot.Launch$.launch(Launch.scala:68)
    at xsbt.boot.Launch$.apply(Launch.scala:14)
    at xsbt.boot.Boot$.runImpl(Boot.scala:24)
    at xsbt.boot.Boot$.main(Boot.scala:15)
    at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: org.jboss.netty.channel.group.ChannelGroup
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 20 more
Error during sbt execution: java.lang.NoClassDefFoundError: org/jboss/netty/channel/group/ChannelGroup

**Comment by arosien** [comment]
Maybe my old cs version?

**Comment by arosien** [comment]
Needed to update to cs 0.3.4, was on 0.3.1.

**Comment by n8han** [comment]
So weird. I guess the launcher in that older version is unable to resolve something, maybe related to the scala-tools move.
