### ISSUE TITLE
implicit.ly front page isn't showing my post

### ISSUE THREAD

**Issue by eed3si9n** [n8han/herald#3]
## steps

```
$ herald --publish
Published sbt-scalashim 0.2.0
-> http://post.ly/6XX0m
```
## problem

http://implicit.y/ front page doesn't include the post for sbt-scalashim 0.2.0.
## expectation

http://implicit.y/ front page includes sbt-scalashim 0.2.0.
## note

hitting http://implicit.ly/sbt-scalashim-020 directly works.

**Comment by n8han** [comment]
Stale cache at posterous.

eugene yokota reply@reply.github.com wrote:

## steps

```
$ herald --publish
Published sbt-scalashim 0.2.0
-> http://post.ly/6XX0m
```

## problem

http://implicit.y/ front page doesn't include the post for sbt-scalashim 0.2.0.

## expectation

http://implicit.y/ front page includes sbt-scalashim 0.2.0.

## note

hitting http://implicit.ly/sbt-scalashim-020 directly works.

---

Reply to this email directly or view it on GitHub:
https://github.com/n8han/herald/issues/3
