### ISSUE TITLE
can't send message on github. README link broken

### ISSUE THREAD

**Issue by xuwei-k** [n8han/herald#4]
I tried send message to @n8han because I want use herald and to be contributor of [implicit.ly](http://implicit.ly/) .
But README link https://github.com/inbox/new/n8han is broken.
I tried search github message feature web page but could not find it.

Maybe github message feature died ?  :(

What should I do?

**Comment by n8han** [comment]
It did indeed! You can email me at nathan@technically.us . You can also fork and fix the readme, if you like. My email is in my github profile and I don't mind it being in the readme too.

**Comment by xuwei-k** [comment]
OK, I have sent mail. thanks
